language: node_js
node_js: stable

# 只监听 source 分支的改动
branches:
  only:
  - source

# 缓存依赖，节省持续集成时间
cache:
  yarn: true
  directories:
    - node_modules
    - themes

before_install:
# 解密 RSA 私钥并设置为本机 ssh 私钥
- openssl aes-256-cbc -K $encrypted_c626fb518bf5_key -iv $encrypted_c626fb518bf5_iv -in .travis/travis.key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
# 修改本机 ssh 配置，防止秘钥认证过程影响自动部署
- mv -fv .travis/ssh-config ~/.ssh/config
- git config --global user.name "zzde"
- git config --global user.email "zhangxh1997@gmail.com"
- yarn global add hexo-cli
# 赋予自动部署脚本可执行权限
- chmod +x .travis/deploy.sh

install:
# 安装 Hexo 及其依赖
- yarn
- yarn add hexo-generator-feed
- yarn add hexo-generator-json-content
# 当 Travis 文件缓存不存在时，从 Gitee 私有仓库 clone 主题
- if [ ! -d "themes/seventeen" ]; then git clone https://github.com/zxh326/hexo-theme-icarus.git themes/icarus; fi
# - git clone https://github.com/zxh326/hexo-theme-icarus.git themes/icarus

script:
# 生成静态页面
- hexo clean
- hexo generate

after_success:
# 部署到 GitHub Pages 和 VPS
# 我把这一部分的操作直接分离到另外的脚本里去了
- .travis/deploy.sh

addons:
  ssh_known_hosts:
  - github.com

